---
- name: Create Directory
  hosts: g1
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: /home/centos/NewDir_fromPlayG1
        state: directory

- name: Install a list of packages
  hosts: n1
  become: true
  tasks:
    - name: Install a list of packages
      ansible.builtin.yum:
        name:
          - git
          - httpd
          - wget
        state: present
